name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with GitHub Stats
        uses: actions/github-script@v3
        with:
          script: |
            const username = 'Snag-hub';
            const token = process.env.GH_TOKEN;

            const statsUrl = `https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=radical&count_private=true`;
            const readmePath = 'README.md';
            const fs = require('fs');
            const content = fs.readFileSync(readmePath, 'utf8');
            const updatedContent = content.replace(
              /\[!\[Syed's GitHub stats\]\([^)]+\)\]/,
              `[![Syed's GitHub stats](${statsUrl})](https://github.com/${username})`
            );
            fs.writeFileSync(readmePath, updatedContent);

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub stats in README"
          branch: main
